"""Regenerate `homepedia_api/tables.py` from the migrated local database (ADR-0002)."""

import sys
from pathlib import Path

import geoalchemy2  # noqa: F401  # registers the PostGIS types for reflection
from sqlacodegen.generators import TablesGenerator
from sqlalchemy import MetaData, create_engine

from homepedia_api.settings import get_settings

HEADER = '''"""Tables and views of the `public` schema, for SQLAlchemy Core.

File generated by `bun run generate` from the local database: do not edit it
by hand. Change the schema in `supabase/migrations`, then run
`bun run supabase:reset` and `bun run generate`.
"""

'''


def main() -> None:
    target = Path(sys.argv[1])
    engine = create_engine(get_settings().sqlalchemy_url)
    metadata = MetaData()
    with engine.connect() as connection:
        metadata.reflect(connection, schema="public", views=True)
        code = TablesGenerator(metadata, connection, options=()).generate()
    engine.dispose()
    target.write_text(HEADER + code)


if __name__ == "__main__":
    main()
